# tomcat
server:
  shutdown: graceful

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%X{requestId}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%class.%method\(%file:%L\)){cyan} %clr(:){faint} %m%n%wEx'
    request: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%X{requestId}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%replace(%logger){'^request\\.', ''}.%X{method}){cyan} %clr(:){faint} %m%n"
    calling: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%X{requestId}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%X{deep} %22X{parent} %m %5X{duration}){yellow} %X{kind} %clr(:){faint} %clr(%replace(%logger){'^calling\\.', ''}:%X{method}){cyan}%n"
    access: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%X{requestId}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%X{method} %m %X{status}){yellow} %X{duration} %X{clientIp} %clr(:){faint} %clr(%X{agent}){cyan}%n'
  level:
    root: "INFO"
    "io.github.dbstarll.algeria": "TRACE"
    org.springframework.boot.context.config.ConfigDataLoaders: "TRACE"
    _org.springframework.web.servlet.HandlerMapping.Mappings: "DEBUG"

# spring
spring:
  application:
    name: algeria-gate
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  redis:
    timeout: 1000
    jedis:
      pool:
        min-idle: 4
        time-between-eviction-runs: 30s
  data:
    redis:
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

algeria-gate:
  version: ${git.commit.id.describe}
  web:
    cors:
      allowed-origins:
        - http://gate.leduo.cn
        - http://gate-api.leduo.cn
  api:
    rbt:
      uri: https://116.63.194.38:17132/apiaccess/gw/rest
      context: /apiaccess/gw/rest
      tone:
        catalog-id: 400960
      user:
        product-id: 13
      system:
        sm-label: sm_send_game_verification_code