spring:
  config:
    encrypt-key: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

algeria-gate:
  api:
    account:
      uri: http://account.test.d02.bst:10080
      secret: "{bC0NWjuMVSFiLR4d}TPmxKkEsiVWtQwyRQezC2JFXqXnsXZ70VT6SrXhBslelsR+p4MDELRvI4+GcQS0n"
